language: python
sudo: false
services:
  - redis-server
  - postgresql
python:
  - "3.6"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip/wheels
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - TRAVIS_NODE_VERSION=8
before_install:
  - bin/update-zeus-job in_progress unknown || echo "failed to report build to Zeus; continuing"
install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn@0.27.5
  - make
script:
  - git --version
  - py.test tests -v --cov . --cov-report="xml:coverage.xml" --junit-xml="junit.xml"
after_success:
  - bin/upload-zeus-artifact junit.xml xunit
  - bin/upload-zeus-artifact coverage.xml coverage
after_failure:
  - bin/upload-zeus-artifact junit.xml xunit
  - bin/upload-zeus-artifact coverage.xml coverage
notifications:
  webhooks:
    urls:
      - $ZEUS_HOOK_BASE/provider/travis/webhook/
