language: python
sudo: false
python:
  - "3.6"
cache:
  directories:
    - .pip_download_cache
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
install:
  - make
script:
  - py.test tests --cov zeus --cov-report term-missing
after_success:
  - codecov
