language: python
sudo: false
python:
  - "3.6"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip/wheels
env:
  global:
    - NODE_ENV=production
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - TRAVIS_NODE_VERSION=8
install:
  - nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn@0.27.5
  - make
script:
  - git --version
  - py.test tests -v --cov zeus --cov-report term-missing
after_success:
  - codecov
