version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - SECRET_KEY=unsafe_secret
      - REDIS_URL=redis://redis/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres@db/postgres
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
